#include "PCH.h"

#include "Diagnostics/Probe.h"

#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/msvc_sink.h>

// ===========================================================================
// SkyrimUpscalerProbe -- standalone diagnostic SKSE plugin.
//
// Deliberately tiny and dependency-light so it compiles and runs first try on
// a real Skyrim SE/AE install. Its only job is to dump the renderer / render-
// target layout (see Diagnostics::DumpAll) to its own log:
//     Documents/My Games/Skyrim Special Edition{,GOG}/SKSE/SkyrimUpscalerProbe.log
// Build just this target with:  xmake build SkyrimUpscalerProbe
// ===========================================================================

namespace
{
	constexpr auto PROBE_NAME = "SkyrimUpscalerProbe"sv;

	void InitializeLog()
	{
		auto path = logger::log_directory();
		if (!path) {
			SKSE::stl::report_and_fail("Failed to locate SKSE log directory");
		}
		*path /= std::format("{}.log", PROBE_NAME);

		auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
		auto log = std::make_shared<spdlog::logger>("global", std::move(sink));
		log->set_level(spdlog::level::info);
		log->flush_on(spdlog::level::info);

		spdlog::set_default_logger(std::move(log));
		spdlog::set_pattern("[%H:%M:%S:%e] [%^%l%$] %v");
	}

	void OnMessage(SKSE::MessagingInterface::Message* a_msg)
	{
		// All SKSE messaging callbacks run on the main thread -- safe to read the
		// renderer here.
		switch (a_msg->type) {
		case SKSE::MessagingInterface::kDataLoaded:
			Diagnostics::DumpAll("kDataLoaded (main menu)", false);
			break;
		case SKSE::MessagingInterface::kPostLoadGame:
			Diagnostics::DumpAll("kPostLoadGame (in world)", true);
			break;
		case SKSE::MessagingInterface::kNewGame:
			Diagnostics::DumpAll("kNewGame (in world)", true);
			break;
		default:
			break;
		}
	}
}

// SKSEPlugin_Version / SKSEPlugin_Query are auto-generated by the
// commonlibsse-ng.plugin rule (name "SkyrimUpscalerProbe" from xmake.lua).

extern "C" DLLEXPORT bool SKSEAPI SKSEPlugin_Load(const SKSE::LoadInterface* a_skse)
{
	InitializeLog();
	logger::info("{} loading (runtime {})", PROBE_NAME, a_skse->RuntimeVersion());

	SKSE::Init(a_skse);

	if (auto* messaging = SKSE::GetMessagingInterface()) {
		messaging->RegisterListener(OnMessage);
	}

	return true;
}
