#include "PCH.h"

#include "Hooks/DX11Hooks.h"
#include "Diagnostics/Probe.h"
#include "Game/Renderer.h"
#include "Neural/NeuralRendering.h"
#include "Settings/Settings.h"
#include "Upscaler/Upscaling.h"
#include "UI/Menu.h"

#include "ENB/ENBSeriesAPI.h"

#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/msvc_sink.h>

// ===========================================================================
// SKSE plugin entry point.
//
// Ported from the Fallout 4 project's XSEPlugin.cpp (F4SE -> SKSE). Target
// runtimes: Steam Skyrim Special Edition 1.5.97 and Anniversary Edition 1.6.x.
// VR and GOG are intentionally out of scope. CommonLibSSE-NG resolves the
// correct addresses per runtime via Address Library, so one DLL covers both
// SE and AE.
// ===========================================================================

// Global with external linkage: the render backend (src/Render/DX12SwapChain)
// links against `extern bool enbLoaded;` to choose the ENB-compatible present path.
bool enbLoaded = false;

namespace
{
	void InitializeLog()
	{
		auto path = logger::log_directory();
		if (!path) {
			SKSE::stl::report_and_fail("Failed to locate SKSE log directory");
		}
		*path /= std::format("{}.log", Plugin::NAME);

		std::shared_ptr<spdlog::logger> log;
#ifndef NDEBUG
		log = std::make_shared<spdlog::logger>("global", std::make_shared<spdlog::sinks::msvc_sink_mt>());
		const auto level = spdlog::level::trace;
#else
		log = std::make_shared<spdlog::logger>(
			"global", std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true));
		const auto level = spdlog::level::info;
#endif
		log->set_level(level);
		log->flush_on(spdlog::level::info);

		spdlog::set_default_logger(std::move(log));
		spdlog::set_pattern("[%H:%M:%S:%e] [%^%l%$] %v");
	}

	void OnMessage(SKSE::MessagingInterface::Message* a_msg)
	{
		switch (a_msg->type) {
		case SKSE::MessagingInterface::kPostPostLoad:
			// Other plugins (incl. SKSE Menu Framework) have loaded. Register
			// the in-game settings page.
			UI::Menu::Register();
			break;
		case SKSE::MessagingInterface::kDataLoaded:
			// Equivalent to F4SE kGameDataReady.
			logger::info("Data loaded");
			{
				Upscaling::GetSingleton()->OnDataLoaded();  // loads settings + menu sink
				auto* store = SettingsStore::GetSingleton();
				auto* neural = NeuralRendering::GetSingleton();
				neural->settings.enableRayReconstruction = store->settings.neuralRayReconstruction != 0;
				neural->settings.enableExternalModules = store->settings.neuralExternalModules != 0;
				neural->Initialize();
			}
			// Diagnostics: dump renderer / render-target layout for the port.
			Diagnostics::DumpAll("kDataLoaded");
			break;
		default:
			break;
		}
	}
}

// NOTE: SKSEPlugin_Version and SKSEPlugin_Query are auto-generated by the
// `commonlibsse-ng.plugin` xmake rule (from the name/author/description/version
// in xmake.lua), so they are intentionally NOT defined here -- defining them
// would collide with the generated plugin.cpp. Only SKSEPlugin_Load is ours.

extern "C" DLLEXPORT bool SKSEAPI SKSEPlugin_Load(const SKSE::LoadInterface* a_skse)
{
	InitializeLog();
	logger::info("{} v{} loading (runtime {})", Plugin::NAME, Plugin::VERSION, a_skse->RuntimeVersion());

	SKSE::Init(a_skse);

	// Trampoline for any REL::Relocation-based hooks in the render backend.
	SKSE::AllocTrampoline(1 << 12);

	// ENB compatibility: probe the ENBSeries modder API. When ENB owns the
	// swapchain, the DX12 proxy path cooperates with it (the Fallout 4 backend
	// already special-cases the "ENB D3D12 proxy swapchain" -- carried over via
	// src/Render/). The ENB SDK is engine-agnostic, so the same header works on
	// Skyrim unchanged.
	if (ENB_API::RequestENBAPI()) {
		logger::info("ENB detected -- enabling ENB-compatible present path");
		enbLoaded = true;
	} else {
		logger::info("ENB not detected");
	}

	DX11Hooks::Install();
	Upscaling::InstallHooks();  // engine render-pipeline hooks (src/Hooks/UpscalerHooks.cpp)

	if (auto* messaging = SKSE::GetMessagingInterface()) {
		messaging->RegisterListener(OnMessage);
	}

	return true;
}
